Create animals table
cancelei/Vet-clinic-DB pull request #1
Opened 2023-08-30 19:23 UTC by cancelei

Hello Reviewer,

Here you find the repo with screen shorts of the filtered table outputs.

Find all animals whose name ends in "mon".
![image](https://github.com/cancelei/Vet-clinic-DB/assets/96393104/b5ea4b7f-ebaf-47f3-a72d-03ee1523722f)

List the name of all animals born between 2016 and 2019.
![image](https://github.com/cancelei/Vet-clinic-DB/assets/96393104/d2424da4-fb9e-411f-b28d-97f9db25b83a)

List the name of all animals that are neutered and have less than 3 escape attempts.
![image](https://github.com/cancelei/Vet-clinic-DB/assets/96393104/f4bb32ee-67d0-41f4-9c7b-6ef3942af6fc)

List the date of birth of all animals named either "Agumon" or "Pikachu".
![image](https://github.com/cancelei/Vet-clinic-DB/assets/96393104/32632615-9523-41e7-88e5-48df8568431d)

List name and escape attempts of animals that weigh more than 10.5kg
![image](https://github.com/cancelei/Vet-clinic-DB/assets/96393104/aabc4796-634d-432f-af16-9110519e6142)

Find all animals that are neutered.
![image](https://github.com/cancelei/Vet-clinic-DB/assets/96393104/766759f9-e6bb-408c-9352-e945e1b01153)

Find all animals not named Gabumon.
![image](https://github.com/cancelei/Vet-clinic-DB/assets/96393104/4ec6188e-73f5-440d-83eb-bc4b1d666ad9)

Find all animals with a weight between 10.4kg and 17.3kg (including the animals with weights that equal precisely 10.4kg or 17.3kg)
![image](https://github.com/cancelei/Vet-clinic-DB/assets/96393104/5fb4f2ad-68e1-41e2-a2a5-0baf27dff1e0)

Happy review.

2023-08-30 20:57 UTC, Ghiftee requested changes
## STATUS: CHANGES REQUIRED ♻️♻️
Hello @cancelei 👋🏽 

Good job working on the project so far! 
To highlight 👍🏽 
✔️ Queries are successful
✔️ Screenshots are added
✔️ SQL commands are put in correct files

However, there are some issues that you need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/59707859/245511452-144e51b1-298e-4041-8d1e-8c012867348c.gif)

## Required Changes ♻️
_Check the comments under the review 👇🏽 _

- [ ] Kindly remove the live demo link from your README since this project is not deployed. It is more professional to have a message such as `coming soon` in place of the broken link.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
- In addition to including an `id` you can mark it as the primary key. Marking your id as primary key, serves many benefits as you continue to build your database

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-08-30 20:57 UTC, Ghiftee commented on schema.sql
> +    name varchar(100),
- [ ] According to the requirements below, the animal table should have the following columns but you are missing the `id` column. It is important to have an `id` for easier distinction of animals. 
```
Create a table named animals with the following columns:
id: integer
name: string
date_of_birth: date
escape_attempts: integer
neutered: boolean
weight_kg: decimal
```

2023-08-30 20:57 UTC, Ghiftee commented on queries.sql
> +SELECT * FROM animals WHERE neutered = true AND escape_attempts < 3;
- [ ] Great job adding these queries, however, you are required to list just the `name` of these animals and not the entire details so your queries should start with `SELECT name ...`

2023-08-30 22:31 UTC, KanzaTahreem requested changes
# Changes Required 🔁

Hi @cancelei 

Great work on making the changes requested by a previous reviewer 👏! I really appreciate the effort you put in!  **_However, there are few this that still need to be fixed. But you are almost there!_** 💪 🏁

![so close](https://media.tenor.com/3sCHnD_x2RIAAAAC/almost-there.gif)


## Highlights 🎯

There are some excellent points that you have made perfectly. Keep up the great work! 👏
- ✅ Table is created
- ✅ Successful queries
- ✅ Screenshots were added

## Required Changes 🛑

_Please check the comments under the review._

## Optional suggestions ❕

- [OPTIONAL] I think it would be better to remove the placeholders (everything that starts with `>`) from the README for making it more professional and clean💪

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-30 22:31 UTC, KanzaTahreem commented on README.md
- [ ] Well done for implementing most of the suggestions 👏 However, I noticed that you missed one from the review summary. Kindly make sure to fix this 👇

![image](https://github.com/cancelei/Vet-clinic-DB/assets/106119105/e9c92812-fdea-4ccc-a9c0-8497d3290dfa)

 _The link is redirecting to the following_

![image](https://github.com/cancelei/Vet-clinic-DB/assets/106119105/58a7f7f9-18d8-41c6-bce3-35cac0a3f147)

2023-08-31 14:31 UTC, youmari approved these changes
# Project Approved :trophy: :tada: 🟢 

Hi @cancelei 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linters error.
:heavy_check_mark: Details PR title and description.
:heavy_check_mark: Good commit messages.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U02FTTCCU2V)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-08-31 14:31 UTC, merged